### PR TITLE
LRAC-9285

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-9285 (test fix)
https://issues.liferay.com/browse/LRAC-9387 (refactor)
https://issues.liferay.com/browse/LRAC-9383 (bug)
https://issues.liferay.com/browse/LRAC-9401 (refactor)
https://issues.liferay.com/browse/LRAC-9402 (refactor)
https://issues.liferay.com/browse/LRAC-9403 (refactor)
https://issues.liferay.com/browse/LRAC-9404 (refactor)
https://issues.liferay.com/browse/LRAC-9405 (refactor)
https://issues.liferay.com/browse/LRAC-9406 (refactor)
https://issues.liferay.com/browse/LRAC-9420 (bug)
https://issues.liferay.com/browse/LRAC-9421 (refactor)
https://issues.liferay.com/browse/LRAC-9422 (refactor)
https://issues.liferay.com/browse/LRAC-9423 (refactor)
https://issues.liferay.com/browse/LRAC-9424 (refactor)
https://issues.liferay.com/browse/LRAC-9425 (refactor)

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by 91nilo** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:stop

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by AfonsoHSantos** [comment]
ci:test:analytics-cloud:nocompile

**Pull request closed without merging**
