### PR TITLE
LRQA-77336 SF

### PR DESCRIPTION
**Pull request by KevinQueiroz**

### CODE REVIEW

**Comment by KevinQueiroz** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LRQA-77336 Test 3 - CanDeleteBlog</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LRQA-77336">Test 3 - CanDeleteBlog</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Subtarefa</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Média</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Kevin Queiroz</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Alex Candido</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 76 insertions(+), 1 deletion(-)

**Comment by KevinQueiroz** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Muito bom @KevinQueiroz, obrigado por isso smile

**Review by AfonsoHSantos — APPROVED** [review]
Muito bom @KevinQueiroz! Parabéns ao time!

**Comment by KevinQueiroz** [comment]
Obrigado!

**Pull request closed without merging**
